apiVersion: v1
kind: Service
metadata:
  name: nodejs-load-balancer
  namespace: app-deploy
spec:
  type: LoadBalancer
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
